/**
 * livekitCallService.ts
 *
 * Handles:
 *  - LiveKit token generation (fetched from the Parva backend — secret never touches the frontend)
 *  - Call signaling via Supabase Realtime Broadcast (no new DB table required)
 *
 * Security model:
 *  - The frontend sends conversationId (never a raw room name).
 *  - The backend verifies membership in conversation_members before issuing a token.
 *  - The backend generates the room name server-side and returns it.
 *  - The frontend uses the server-returned roomName for the LiveKit connection.
 *
 * Signaling channel: `call-signals`
 * Broadcast events:
 *  - `call:ring`    – caller → callee: incoming call notification
 *  - `call:accept`  – callee → caller: call accepted, ready to join room
 *  - `call:decline` – callee → caller: call declined
 *  - `call:cancel`  – caller → callee: caller hung up before answer
 *  - `call:end`     – either party: call ended (both should disconnect)
 */

import { supabase } from '../lib/supabase'

const API_BASE = import.meta.env.VITE_API_URL || ''

// ── Types ──────────────────────────────────────────────────────────────────

export type CallType = 'voice' | 'video'

export interface CallSignalPayload {
  /** Unique call session id (UUID generated by caller) */
  callId: string
  /** Supabase employee UUID of the caller */
  callerId: string
  callerName: string
  /**
   * For direct calls: the callee's employee UUID.
   * For group calls: the group/conversation UUID.
   */
  calleeId: string
  /** true if this is a group call */
  isGroup: boolean
  groupName?: string
  callType: CallType
  /**
   * The Supabase conversation UUID used to obtain the LiveKit room.
   * Both parties call fetchLiveKitToken({ conversationId }) to get a token
   * for the same server-side room. Never a raw room name.
   */
  conversationId: string
}

export type SignalEvent =
  | 'call:ring'
  | 'call:accept'
  | 'call:decline'
  | 'call:cancel'
  | 'call:end'

// ── Token fetching ─────────────────────────────────────────────────────────

/**
 * Fetches a LiveKit access token from the Parva backend.
 *
 * The backend verifies:
 *  1. The caller is authenticated.
 *  2. The caller is a member of the given conversation.
 * Then returns a token for the server-computed room "lk_conv_<conversationId>".
 *
 * @param conversationId  The Supabase conversation UUID (direct or group).
 */
export async function fetchLiveKitToken(
  conversationId: string
): Promise<{ token: string; serverUrl: string; roomName: string }> {
  const { data: sessionData } = await supabase.auth.getSession()
  const accessToken = sessionData?.session?.access_token
  if (!accessToken) throw new Error('Not authenticated')

  const res = await fetch(`${API_BASE}/api/livekit/token`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${accessToken}`,
    },
    body: JSON.stringify({ conversationId }),
  })

  if (!res.ok) {
    const body = await res.json().catch(() => ({}))
    throw new Error((body as { message?: string }).message || `Token fetch failed (${res.status})`)
  }

  return res.json() as Promise<{ token: string; serverUrl: string; roomName: string }>
}

// ── Signaling ──────────────────────────────────────────────────────────────

/**
 * Broadcasts a call signal on the shared `call-signals` Supabase Realtime channel.
 * All authenticated clients are subscribed; each filters by calleeId / callerId.
 */
export async function broadcastCallSignal(
  event: SignalEvent,
  payload: Partial<CallSignalPayload> & { callId: string }
): Promise<void> {
  const channel = supabase.channel('call-signals')
  await new Promise<void>((resolve) => {
    channel.subscribe((status) => {
      if (status === 'SUBSCRIBED') resolve()
    })
  })
  await channel.send({ type: 'broadcast', event, payload })
  supabase.removeChannel(channel)
}

/**
 * Subscribe to incoming call signals for a specific employee.
 *
 * @param myEmployeeId  The authenticated employee's UUID.
 * @param myGroupIds    UUIDs of all groups/conversations this employee belongs to.
 *                      Used to filter group call signals so that only members of the
 *                      relevant group see them. Must be kept current as membership changes.
 * @param onSignal      Callback invoked for signals that pass the recipient filter.
 *
 * Returns an unsubscribe function.
 *
 * Filtering rules (client-side guard — backend token endpoint is the hard auth boundary):
 *
 *  call:ring
 *    Direct: pass only if calleeId === myEmployeeId (not own outgoing)
 *    Group:  pass only if myGroupIds.includes(calleeId) (not own outgoing)
 *
 *  call:accept / call:end
 *    Direct: pass if calleeId === myEmployeeId OR callerId === myEmployeeId
 *    Group:  pass if myGroupIds.includes(calleeId) OR callerId === myEmployeeId
 *
 *  call:decline
 *    Pass only to the original caller (callerId === myEmployeeId)
 *
 *  call:cancel
 *    Direct: pass only to callee (calleeId === myEmployeeId)
 *    Group:  pass to any group member (myGroupIds.includes(calleeId))
 */
export function subscribeToCallSignals(
  myEmployeeId: string,
  myGroupIds: string[],
  onSignal: (event: SignalEvent, payload: CallSignalPayload) => void
): () => void {
  // Helper: true only if the signal targets a group this employee is a member of
  const isMemberOfGroup = (p: CallSignalPayload) =>
    p.isGroup && myGroupIds.includes(p.calleeId)

  const channel = supabase
    .channel('call-signals')
    .on('broadcast', { event: 'call:ring' }, ({ payload }) => {
      const p = payload as CallSignalPayload
      if (p.callerId === myEmployeeId) return // ignore own outgoing signals

      if (p.isGroup) {
        // Group call: ONLY members of that specific group see the ring
        if (!isMemberOfGroup(p)) return
      } else {
        // Direct call: ONLY the intended callee sees the ring
        if (p.calleeId !== myEmployeeId) return
      }

      onSignal('call:ring', p)
    })
    .on('broadcast', { event: 'call:accept' }, ({ payload }) => {
      const p = payload as CallSignalPayload
      // Accept flows back to caller; for group calls all members should know call is live
      const isParty =
        p.callerId === myEmployeeId ||
        p.calleeId === myEmployeeId ||
        isMemberOfGroup(p)
      if (!isParty) return
      onSignal('call:accept', p)
    })
    .on('broadcast', { event: 'call:decline' }, ({ payload }) => {
      const p = payload as CallSignalPayload
      // Decline only matters to the original caller
      if (p.callerId !== myEmployeeId) return
      onSignal('call:decline', p)
    })
    .on('broadcast', { event: 'call:cancel' }, ({ payload }) => {
      const p = payload as CallSignalPayload
      // Cancel: direct callee or any member of the target group
      const isTarget = p.calleeId === myEmployeeId || isMemberOfGroup(p)
      if (!isTarget) return
      onSignal('call:cancel', p)
    })
    .on('broadcast', { event: 'call:end' }, ({ payload }) => {
      const p = payload as CallSignalPayload
      // End: direct parties or any group member
      const isParty =
        p.calleeId === myEmployeeId ||
        p.callerId === myEmployeeId ||
        isMemberOfGroup(p)
      if (!isParty) return
      onSignal('call:end', p)
    })
    .subscribe()

  return () => {
    supabase.removeChannel(channel)
  }
}
